# Generated by Django 3.1.7 on 2021-04-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='code',
            new_name='room_code',
        ),
    ]
