# Generated by Django 3.1.7 on 2021-04-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_room_block_answers'),
        ('api', '0004_auto_20210415_1512'),
    ]

    operations = [
    ]
