# Generated by Django 3.1.7 on 2021-05-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210513_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='trivia',
            field=models.CharField(default='', max_length=300),
        ),
    ]
