# Generated by Django 3.1.7 on 2021-05-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210513_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='quiz_type',
            field=models.CharField(default='classics', max_length=20),
        ),
    ]
