# Generated by Django 3.1.7 on 2021-05-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_song_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='quiz_type',
        ),
    ]
