# Generated by Django 3.1.7 on 2021-05-14 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20210416_0912'),
        ('api', '0012_song_types'),
    ]

    operations = [
    ]
