# Generated by Django 3.1.7 on 2021-05-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_room_quiz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='quiz_type',
            field=models.CharField(default='classics', max_length=20),
        ),
    ]
